name: Build

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: --skip-publish --clean
      - name: Upload
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          tag_name="${GITHUB_REF##*/}"
          gh release upload  "$tag_name" $(find dist -type f -name "*.tar.gz" -printf "%p ") "dist/checksums.txt"
      - name: Upload Homebrew formula
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          BOT_USERNAME: ${{secrets.BOT_USERNAME}}
          BOT_EMAIL: ${{secrets.BOT_EMAIL}}
        run: |
          git config --global user.email "${BOT_EMAIL}"
          git config --global user.name "${BOT_USERNAME}"
          tag_name="${GITHUB_REF##*/}"
          cd dist
          git clone "https://git:${GITHUB_TOKEN}@github.com/getstrm/homebrew-cli.git"
          cp -f homebrew/Formula/pace.rb homebrew-cli
          cd homebrew-cli
          git add .
          git commit -m "Release brew formula for Pace CLI ${tag_name}"
          git push
          git tag -a "${tag_name}" -m "Release brew formula for Pace CLI ${tag_name}"
          git push --tags
      - name: Update CLI docs
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          BOT_USERNAME: ${{secrets.BOT_USERNAME}}
          BOT_EMAIL: ${{secrets.BOT_EMAIL}}
        run: |
          make docs
          git config --global user.email "${BOT_EMAIL}"
          git config --global user.name "${BOT_USERNAME}"
          git clone "https://git:${GITHUB_TOKEN}@github.com/getstrm/pace.git"
          cd pace
          git checkout alpha
          cd ..
          python ./scripts/update_summary.py
          cp -r ./generated_docs/pace* pace/docs/cli-docs
          cd pace
          git add ./docs 
          git commit -m "docs: update docs for Pace CLI ${tag_name}"
          git push origin -u $(git branch --show-current)
