name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i --non-interactive --pure-lockfile
      - name: Release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GIT_AUTHOR_NAME: ${{secrets.BOT_USERNAME}}
          GIT_COMMITTER_NAME: ${{secrets.BOT_USERNAME}}
          GIT_AUTHOR_EMAIL: ${{secrets.BOT_EMAIL}}
          GIT_COMMITTER_EMAIL: ${{secrets.BOT_EMAIL}}
        run: npm run semantic-release -- --repository-url "$(git config --get remote.origin.url)"
